[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
circuit = { path = "../circuit", features = ["default_conductors"] }

egui_extras = { version = "*", features = ["default", "all_loaders"] }
eframe = "0.28.1"
egui = "0.28.1"
